
const comicManifest = {"scenes": [{"page_number": 0, "name": "", "file_name": "", "contents_image": "img/preview/0.png"}, {"page_number": 1, "name": "", "file_name": "", "contents_image": "img/preview/00.png"}, {"page_number": 2, "name": "1", "file_name": "", "contents_image": "img/preview/01.png"}, {"page_number": 3, "name": "2", "file_name": "", "contents_image": "img/preview/02.png"}, {"page_number": 4, "name": "3", "file_name": "", "contents_image": "img/preview/03.png"}, {"page_number": 5, "name": "4", "file_name": "", "contents_image": "img/preview/04.png"}, {"page_number": 6, "name": "5", "file_name": "", "contents_image": "img/preview/05.png"}, {"page_number": 7, "name": "6", "file_name": "", "contents_image": "img/preview/06.png"}, {"page_number": 8, "name": "7", "file_name": "", "contents_image": "img/preview/07.png"}, {"page_number": 9, "name": "8", "file_name": "", "contents_image": "img/preview/08.png"}, {"page_number": 10, "name": "9", "file_name": "", "contents_image": "img/preview/09.png"}, {"page_number": 11, "name": "10", "file_name": "", "contents_image": "img/preview/10.png"}, {"page_number": 12, "name": "11", "file_name": "", "contents_image": "img/preview/11.png"}, {"page_number": 13, "name": "12", "file_name": "", "contents_image": "img/preview/12.png"}, {"page_number": 14, "name": "13", "file_name": "", "contents_image": "img/preview/13.png"}], "languages": ["ru", "en", "es", "ko"]};
const comicSceneCount = comicManifest.scenes.length;
const comicSupportedLanguages = comicManifest.languages;
const languageOptions=[
 {code:"uk",name:"Українська"},
 {code:"en",name:"English"},
 {code:"pl",name:"Polski"},
 {code:"de",name:"Deutsch"},
 {code:"fr",name:"Français"},
 {code:"es",name:"Español"}
];
const comicLanguageNames={ru:"Русский",en:"English",es:"Español",ko:"한국어"};
const i18n={
 uk:{comicLabel:"КОМІКС",comicTitle:"PandaBum + WebIntCom Player",language:"Мова інтерфейсу",comicLanguage:"Мова коміксу",comicLanguageNote:"Доступні тільки мови, які є в архіві коміксу.",launch:"▶ Запустити Player",loading:"Завантаження Player...",settings:"Налаштування",hints:"Підказки",musicVolume:"Гучність коміксу",soundOff:"Звук вимкнено",soundOffButton:"Звук вимкнено кнопкою",scene:"Сцена",back:"← Назад",next:"Далі →",restart:"↻ Перезапуск",pause:"⏸ Пауза",resume:"▶ Продовжити",replay:"⟳ Повтор сцени",hintDefault:"Підказка: якщо сцена зупинилась, шукай натискання, свайп або інтерактивну область прямо всередині коміксу.",hintDisabled:"Підказки вимкнені. Увімкнути їх можна в ⚙️ Налаштуваннях.",statusLabel:"Статус",statusReady:"Комікс готовий",statusLoading:"Підключення до коміксу...",statusError:"Не вдалося завантажити комікс",statusScene:"Поточна сцена",statusLanguage:"Мова коміксу",previewScene:"Сцена",serviceSceneIntro:"Відкрита сцена",servicePaused:"Комікс поставлено на паузу",serviceResumed:"Комікс продовжено",serviceRestarted:"Комікс перезапущено з початку",serviceComicLanguageChanged:"Мову коміксу змінено. Плеєр перезавантажено.",serviceHint:"Підказка: взаємодій із елементами прямо всередині коміксу.",bridgeWaiting:"Очікування рушія NARR8...",bridgeConnected:"Рушій NARR8 підключено"},
 en:{comicLabel:"COMIC",comicTitle:"PandaBum + WebIntCom Player",language:"Interface language",comicLanguage:"Comic language",comicLanguageNote:"Only languages included in the comic archive are available.",launch:"▶ Launch Player",loading:"Loading Player...",settings:"Settings",hints:"Hints",musicVolume:"Comic volume",soundOff:"Sound off",soundOffButton:"Sound muted",scene:"Scene",back:"← Back",next:"Next →",restart:"↻ Restart",pause:"⏸ Pause",resume:"▶ Resume",replay:"⟳ Replay scene",hintDefault:"Hint: if the scene stops, look for a tap, swipe, or interactive area inside the comic.",hintDisabled:"Hints are off. You can enable them in ⚙️ Settings.",statusLabel:"Status",statusReady:"Comic ready",statusLoading:"Connecting to comic...",statusError:"Comic failed to load",statusScene:"Current scene",statusLanguage:"Comic language",previewScene:"Scene",serviceSceneIntro:"Opened scene",servicePaused:"Comic paused",serviceResumed:"Comic resumed",serviceRestarted:"Comic restarted from the beginning",serviceComicLanguageChanged:"Comic language changed. Player reloaded.",serviceHint:"Hint: interact with the elements inside the comic.",bridgeWaiting:"Waiting for NARR8 engine...",bridgeConnected:"NARR8 engine connected"}
};
const narratorUi={
 uk:{narrator:"Диктор",voiceLanguage:"Мова озвучення",autoLanguage:"Авто — мова інтерфейсу",autoNote:"Авто використовує мову інтерфейсу Player.",narratorVolume:"Гучність диктора",replay:"Переграти",stop:"Зупинити",speed:"Швидкість",unsupported:"Диктор не підтримується цим браузером."},
 en:{narrator:"Narrator",voiceLanguage:"Narration language",autoLanguage:"Auto — interface language",autoNote:"Auto follows the Player interface language.",narratorVolume:"Narrator volume",replay:"Replay",stop:"Stop",speed:"Speed",unsupported:"Narration is not supported by this browser."}
};
let currentLanguage="uk", comicLanguage="en", currentScene=0, maxReachedScene=0, playerStarted=false, hintsEnabled=true, toastTimer=null;
let volume=0.7, comicMuted=false, narratorEnabled=false, narratorLanguage="auto", narratorVolume=1, narratorRate=1, currentUtterance=null, lastNarrationType="scene";
let comicFrame=null, comicApi=null, comicReady=false, comicPaused=false, bridgePollTimer=null, resizeObserver=null;
const preview=document.getElementById("preview"), playerContainer=document.getElementById("playerContainer"), launchButton=document.getElementById("launchButton"), loading=document.getElementById("loading"), launchLanguage=document.getElementById("launchLanguage"), launchComicLanguage=document.getElementById("launchComicLanguage"), launchNarratorToggle=document.getElementById("launchNarratorToggle"), launchNarratorLanguage=document.getElementById("launchNarratorLanguage"), launchNarratorLanguageWrap=document.getElementById("launchNarratorLanguageWrap"), previewStrip=document.getElementById("previewStrip");
function t(){return i18n[currentLanguage]||i18n.uk}
function nt(){return narratorUi[currentLanguage]||narratorUi.uk}
function fillLanguageSelect(select){select.innerHTML="";languageOptions.forEach(lang=>{const o=document.createElement("option");o.value=lang.code;o.textContent=lang.name;select.appendChild(o)});select.value=currentLanguage;}
function resolveDefaultComicLanguage(){if(comicSupportedLanguages.includes(currentLanguage)) return currentLanguage; return comicSupportedLanguages.includes('en') ? 'en' : comicSupportedLanguages[0];}
function fillComicLanguageSelect(select){select.innerHTML="";comicSupportedLanguages.forEach(code=>{const o=document.createElement("option");o.value=code;o.textContent=comicLanguageNames[code]||code;select.appendChild(o)}); if(!comicSupportedLanguages.includes(comicLanguage)) comicLanguage=resolveDefaultComicLanguage(); select.value=comicLanguage;}
function fillNarratorLanguageSelect(select){select.innerHTML="";const auto=document.createElement("option");auto.value="auto";auto.textContent=nt().autoLanguage;select.appendChild(auto);languageOptions.forEach(lang=>{const o=document.createElement("option");o.value=lang.code;o.textContent=lang.name;select.appendChild(o)});select.value=narratorLanguage;}
function syncLanguageSelectors(){launchLanguage.value=currentLanguage; const settingsLanguage=document.getElementById('settingsLanguage'); if(settingsLanguage) settingsLanguage.value=currentLanguage; const settingsNarratorLanguage=document.getElementById('settingsNarratorLanguage'); if(settingsNarratorLanguage) settingsNarratorLanguage.value=narratorLanguage; if(launchNarratorLanguage) launchNarratorLanguage.value=narratorLanguage; const settingsComicLanguage=document.getElementById('settingsComicLanguage'); if(settingsComicLanguage) settingsComicLanguage.value=comicLanguage; if(launchComicLanguage) launchComicLanguage.value=comicLanguage;}
function buildPreviewStrip(){previewStrip.innerHTML=''; comicManifest.scenes.forEach((scene,index)=>{const img=document.createElement('img'); img.src='comic-data/'+scene.contents_image; img.alt='Scene '+(index+1); if(index===currentScene) img.classList.add('active'); img.onclick=()=>{ if(!playerStarted) return; if(index<=maxReachedScene) jumpToScene(index,true); }; previewStrip.appendChild(img);});}
function updatePreviewStrip(){[...previewStrip.children].forEach((img,i)=>img.classList.toggle('active',i===currentScene));}
function setLanguage(code){if(!i18n[code]) code='uk'; if(playerStarted && currentUtterance) stopNarrator(); currentLanguage=code; document.documentElement.lang=code; syncLanguageSelectors(); document.getElementById('comicLabel').textContent=t().comicLabel; document.getElementById('comicTitle').textContent=t().comicTitle; document.getElementById('launchLanguageLabel').textContent=t().language; document.getElementById('launchComicLanguageLabel').textContent=t().comicLanguage; document.getElementById('launchComicLanguageNote').textContent=t().comicLanguageNote; document.getElementById('launchNarratorLabel').textContent=nt().narrator; document.getElementById('launchNarratorLanguageLabel').textContent=nt().voiceLanguage; document.getElementById('launchNarratorNote').textContent=nt().autoNote; fillNarratorLanguageSelect(launchNarratorLanguage); launchButton.textContent=t().launch; document.getElementById('loadingText').textContent=t().loading; if(playerStarted) translatePlayerUI();}
function effectiveNarratorLanguage(){return narratorLanguage==='auto'?currentLanguage:narratorLanguage}
const speechLangMap={uk:'uk-UA',en:'en-US',pl:'pl-PL',de:'de-DE',fr:'fr-FR',es:'es-ES'};
function getSpeechVoice(langTag){if(!('speechSynthesis' in window)) return null; const voices=window.speechSynthesis.getVoices(); const exact=voices.find(v=>v.lang.toLowerCase()===langTag.toLowerCase()); if(exact) return exact; const base=langTag.split('-')[0].toLowerCase(); return voices.find(v=>v.lang.toLowerCase().startsWith(base))||null;}
function stopNarrator(){if('speechSynthesis' in window) window.speechSynthesis.cancel(); currentUtterance=null;}
function speakNarratorText(text,type='scene'){if(!narratorEnabled||!playerStarted||!text) return; if(!('speechSynthesis' in window)){showNarratorUnsupported();return} stopNarrator(); const langCode=effectiveNarratorLanguage(); const utter=new SpeechSynthesisUtterance(text); utter.lang=speechLangMap[langCode]||speechLangMap.uk; const voice=getSpeechVoice(utter.lang); if(voice) utter.voice=voice; utter.volume=narratorVolume; utter.rate=narratorRate; utter.pitch=1; currentUtterance=utter; lastNarrationType=type; utter.onend=()=>{if(currentUtterance===utter) currentUtterance=null}; utter.onerror=()=>{if(currentUtterance===utter) currentUtterance=null}; window.speechSynthesis.speak(utter);}
function speakCurrentScene(){speakNarratorText(`${t().serviceSceneIntro} ${currentScene+1}.`, 'scene')}
function speakHint(){speakNarratorText(t().serviceHint,'hint')}
function replayNarrator(){if(lastNarrationType==='hint') speakHint(); else speakCurrentScene();}
function showNarratorUnsupported(){const toast=document.getElementById('settingsToast'); if(!toast) return; toast.textContent=nt().unsupported; toast.classList.add('show'); clearTimeout(toastTimer); toastTimer=setTimeout(()=>toast.classList.remove('show'),3200);}
function updateNarratorUI(){const controls=document.getElementById('narratorControls'),volumeSection=document.getElementById('narratorVolumeSection'),settingsWrap=document.getElementById('settingsNarratorLanguageWrap'); const settingsToggle=document.getElementById('narratorToggle'),settingsSelect=document.getElementById('settingsNarratorLanguage'); if(controls) controls.classList.toggle('active',narratorEnabled); if(volumeSection) volumeSection.classList.toggle('hidden',!narratorEnabled); if(settingsWrap) settingsWrap.classList.toggle('show',narratorEnabled); if(settingsToggle) settingsToggle.checked=narratorEnabled; if(settingsSelect) settingsSelect.value=narratorLanguage; launchNarratorToggle.checked=narratorEnabled; launchNarratorLanguageWrap.classList.toggle('hidden',!narratorEnabled); launchNarratorLanguage.value=narratorLanguage;}
function setNarratorEnabled(enabled){narratorEnabled=!!enabled; if(!narratorEnabled) stopNarrator(); updateNarratorUI();}
function setNarratorLanguage(code){if(playerStarted&&currentUtterance) stopNarrator(); narratorLanguage=code; if(launchNarratorLanguage) launchNarratorLanguage.value=code; const settingsSelect=document.getElementById('settingsNarratorLanguage');if(settingsSelect) settingsSelect.value=code;}
function setNarratorVolume(v){narratorVolume=Number(v); const label=document.getElementById('narratorVolumeValue'); if(label) label.textContent=Math.round(narratorVolume*100)+'%'; if(narratorEnabled&&playerStarted&&currentUtterance) replayNarrator();}
function setNarratorRate(v){narratorRate=Number(v); if(narratorEnabled&&playerStarted&&currentUtterance) replayNarrator();}
function updateSoundUI(){const label=document.getElementById('volumeValue'); const status=document.getElementById('soundStatus'); const b=document.getElementById('soundButton'); const percent=Math.round(volume*100); if(label) label.textContent=percent+'%'; const effectivelyMuted=comicMuted||volume===0; if(b) b.textContent=effectivelyMuted?'🔇':'🔊'; if(status) status.textContent=volume===0?t().soundOff:(comicMuted?t().soundOffButton:'');}
function applyComicVolume(){if(comicApi && comicApi.setVolume){try{comicApi.setVolume(comicMuted?0:volume)}catch(e){console.warn(e)}} updateSoundUI();}
function setVolume(v){volume=Number(v); applyComicVolume();}
function setComicLanguage(code, reload=true){if(!comicSupportedLanguages.includes(code)) return; comicLanguage=code; syncLanguageSelectors(); const note=document.getElementById('launchComicLanguageNote'); if(note) note.textContent=t().comicLanguageNote; if(reload && playerStarted){loadComic(true); const toast=document.getElementById('settingsToast'); if(toast){toast.textContent=t().serviceComicLanguageChanged; toast.classList.add('show'); clearTimeout(toastTimer); toastTimer=setTimeout(()=>toast.classList.remove('show'),3200);}}}
function createPlayer(){playerContainer.innerHTML=`
<div class="player-header">
 <div class="player-logo">WebIntCom Player</div>
 <div class="header-right">
  <button class="sound-button" id="soundButton" title="Comic sound">🔊</button>
  <button class="pause-button" id="pauseButton">⏸</button>
  <button class="settings-button" id="settingsButton" title="Settings">⚙️</button>
  <button class="scene-counter" id="sceneCounter"></button>
 </div>
</div>
<div class="scene-wrap">
 <div class="scene-menu" id="sceneMenu"></div>
 <div class="sound-panel" id="soundPanel">
  <div class="sound-section">
   <div id="musicVolumeLabel" style="font-size:13px;margin-bottom:9px"></div>
   <div class="sound-row"><input id="volumeSlider" type="range" min="0" max="1" step=".01" value="${volume}"><span class="sound-value" id="volumeValue">${Math.round(volume*100)}%</span></div>
   <div class="sound-status" id="soundStatus"></div>
  </div>
  <div class="sound-section narrator-volume-section hidden" id="narratorVolumeSection">
   <div id="narratorVolumeLabel" style="font-size:13px;margin-bottom:9px"></div>
   <div class="sound-row"><input id="narratorVolumeSlider" type="range" min="0" max="1" step=".01" value="${narratorVolume}"><span class="sound-value" id="narratorVolumeValue">${Math.round(narratorVolume*100)}%</span></div>
  </div>
 </div>
 <div class="settings-panel" id="settingsPanel">
  <div class="settings-title" id="settingsTitle"></div>
  <div class="settings-row"><span id="hintsLabel"></span><label class="switch"><input id="hintsToggle" type="checkbox"><span class="switch-slider"></span></label></div>
  <div class="settings-row language-row"><label id="settingsLanguageLabel" for="settingsLanguage"></label><select class="language-select" id="settingsLanguage"></select></div>
  <div class="settings-row language-row"><label id="settingsComicLanguageLabel" for="settingsComicLanguage"></label><select class="language-select" id="settingsComicLanguage"></select></div>
  <div class="settings-row"><span id="narratorLabel"></span><label class="switch"><input id="narratorToggle" type="checkbox"><span class="switch-slider"></span></label></div>
  <div class="settings-row language-row narrator-settings-language" id="settingsNarratorLanguageWrap"><label id="settingsNarratorLanguageLabel" for="settingsNarratorLanguage"></label><select class="language-select" id="settingsNarratorLanguage"></select></div>
 </div>
</div>
<div class="stage" id="stage">
 <div class="settings-toast" id="settingsToast"></div>
 <iframe class="comic-frame" id="comicFrame" title="NARR8 comic"></iframe>
 <div class="hint hidden" id="hint"></div>
</div>
<div class="controls">
 <div class="nav-controls"><button id="previousButton"></button><button id="nextButton"></button><button id="restartButton"></button><button id="replaySceneButton"></button><button id="hintButton">?</button></div>
 <div class="narrator-controls" id="narratorControls"><span class="narrator-badge" title="Narrator">🎙️</span><button id="narratorReplayButton"></button><button id="narratorStopButton"></button><select class="rate-select" id="narratorRateSelect" aria-label="Narrator speed"><option value="0.75">0.75×</option><option value="1" selected>1×</option><option value="1.25">1.25×</option><option value="1.5">1.5×</option><option value="2">2×</option></select></div>
</div>
<div class="status-bar"><div><strong id="statusTitle"></strong>: <span id="statusValue"></span></div><div><strong id="statusSceneTitle"></strong>: <span id="statusSceneValue"></span></div><div><strong id="statusLanguageTitle"></strong>: <span id="statusLanguageValue"></span></div></div>
<div class="player-footer">WebIntCom Player + NARR8 bridge</div>`;
 const sceneCounter=document.getElementById('sceneCounter'), sceneMenu=document.getElementById('sceneMenu'), soundButton=document.getElementById('soundButton'), soundPanel=document.getElementById('soundPanel'), volumeSlider=document.getElementById('volumeSlider'), settingsButton=document.getElementById('settingsButton'), settingsPanel=document.getElementById('settingsPanel'), hintsToggle=document.getElementById('hintsToggle'), settingsLanguage=document.getElementById('settingsLanguage'), settingsComicLanguage=document.getElementById('settingsComicLanguage'), narratorToggle=document.getElementById('narratorToggle'), settingsNarratorLanguage=document.getElementById('settingsNarratorLanguage'), narratorVolumeSlider=document.getElementById('narratorVolumeSlider'), narratorReplayButton=document.getElementById('narratorReplayButton'), narratorStopButton=document.getElementById('narratorStopButton'), narratorRateSelect=document.getElementById('narratorRateSelect');
 const previousButton=document.getElementById('previousButton'), nextButton=document.getElementById('nextButton'), restartButton=document.getElementById('restartButton'), replaySceneButton=document.getElementById('replaySceneButton'), hint=document.getElementById('hint'), pauseButton=document.getElementById('pauseButton'), hintButton=document.getElementById('hintButton');
 comicFrame=document.getElementById('comicFrame');
 fillLanguageSelect(settingsLanguage); fillComicLanguageSelect(settingsComicLanguage); fillNarratorLanguageSelect(settingsNarratorLanguage); settingsLanguage.value=currentLanguage; settingsComicLanguage.value=comicLanguage; settingsNarratorLanguage.value=narratorLanguage; narratorToggle.checked=narratorEnabled; narratorRateSelect.value=String(narratorRate);
 function renderMenu(){sceneMenu.innerHTML=''; comicManifest.scenes.forEach((s,i)=>{const b=document.createElement('button'); const label=s.name ? `${i+1}. ${s.name}` : `${t().previewScene} ${i+1}`; b.textContent=label; b.disabled=i>maxReachedScene; if(i>maxReachedScene) b.classList.add('locked'); if(i===currentScene) b.classList.add('current'); b.onclick=()=>{if(i<=maxReachedScene){sceneMenu.classList.remove('open'); jumpToScene(i,true);}}; sceneMenu.appendChild(b);}); }
 function updateSceneUI(){sceneCounter.textContent=`${t().scene} ${currentScene+1} / ${comicSceneCount}`; previousButton.disabled=currentScene===0; nextButton.disabled=currentScene>=comicSceneCount-1; document.getElementById('statusSceneValue').textContent=`${currentScene+1} / ${comicSceneCount}`; updatePreviewStrip(); renderMenu(); pauseButton.textContent=comicPaused ? '▶' : '⏸'; pauseButton.title=comicPaused ? t().resume : t().pause;}
 function showHint(){if(hintsEnabled){hint.textContent=t().hintDefault; hint.classList.remove('hidden'); if(narratorEnabled) speakHint();} else {hint.classList.add('hidden'); const toast=document.getElementById('settingsToast'); toast.textContent=t().hintDisabled; toast.classList.add('show'); clearTimeout(toastTimer); toastTimer=setTimeout(()=>toast.classList.remove('show'),3200);}}
 function jumpToScene(index,userInitiated=false){if(index<0 || index>=comicSceneCount) return; currentScene=index; if(currentScene>maxReachedScene) maxReachedScene=currentScene; if(comicApi && comicReady && comicApi.goToScene){try{comicApi.goToScene(index);}catch(e){console.warn(e);}} updateSceneUI(); hint.classList.add('hidden'); if(userInitiated && narratorEnabled) speakCurrentScene();}
 function previousScene(){if(currentScene>0) jumpToScene(currentScene-1,true)}
 function nextScene(){if(currentScene<comicSceneCount-1) jumpToScene(currentScene+1,true)}
 function restart(){maxReachedScene=0; jumpToScene(0,true); const toast=document.getElementById('settingsToast'); toast.textContent=t().serviceRestarted; toast.classList.add('show'); clearTimeout(toastTimer); toastTimer=setTimeout(()=>toast.classList.remove('show'),3200);}
 function replayScene(){jumpToScene(currentScene,true)}
 function togglePause(){if(!comicApi||!comicReady) return; try{ if(comicPaused){comicApi.resume(); comicPaused=false; if(narratorEnabled) speakNarratorText(t().serviceResumed,'service');} else {comicApi.pause(); comicPaused=true; if(narratorEnabled) speakNarratorText(t().servicePaused,'service');} updateSceneUI();}catch(e){console.warn(e)}}
 function bindBridgeHandlers(api){api.engineIsReadyHandler=()=>{comicReady=true; comicPaused=false; document.getElementById('statusValue').textContent=t().bridgeConnected; applyComicVolume(); syncViewport(); updateSceneUI(); if(narratorEnabled) speakCurrentScene();}; api.setSectionNumberHandler=(sceneIndex,total)=>{ if(Number.isFinite(sceneIndex)) currentScene=Number(sceneIndex); if(Number.isFinite(sceneIndex) && currentScene>maxReachedScene) maxReachedScene=currentScene; updateSceneUI(); }; api.sectionFinishedHandler=(sceneIndex)=>{ if(typeof sceneIndex==='number' && sceneIndex>=maxReachedScene) maxReachedScene=Math.min(comicSceneCount-1,sceneIndex+1); updateSceneUI(); }; api.resourceLoadErrorHandler=(error)=>{ document.getElementById('statusValue').textContent=t().statusError; console.error('NARR8 resource error', error); }; api.setProgressHandler=(progress)=>{ if(progress>=1 && document.getElementById('statusValue').textContent!==t().bridgeConnected) document.getElementById('statusValue').textContent=t().statusReady; }; }
 function syncViewport(){ if(!comicApi||!comicApi.setViewportSize) return; const rect=document.getElementById('stage').getBoundingClientRect(); try{comicApi.setViewportSize(Math.round(rect.width), Math.round(rect.height));}catch(e){console.warn(e)} }
 function connectBridge(){ clearInterval(bridgePollTimer); document.getElementById('statusValue').textContent=t().bridgeWaiting; bridgePollTimer=setInterval(()=>{ try{ const frameWindow=comicFrame.contentWindow; if(!frameWindow) return; if(frameWindow.engineAPI){ comicApi=frameWindow.engineAPI; bindBridgeHandlers(comicApi); clearInterval(bridgePollTimer); bridgePollTimer=null; applyComicVolume(); syncViewport(); } }catch(e){} }, 250); }
 function loadComic(force=false){ comicReady=false; comicApi=null; comicPaused=false; document.getElementById('statusValue').textContent=t().statusLoading; const url=`comic-data/canvas.html?lang=${encodeURIComponent(comicLanguage)}&_=${force?Date.now():1}`; comicFrame.src=url; connectBridge(); document.getElementById('statusLanguageValue').textContent=comicLanguageNames[comicLanguage]||comicLanguage; }
 sceneCounter.onclick=()=>{sceneMenu.classList.toggle('open'); soundPanel.classList.remove('open'); settingsPanel.classList.remove('open')};
 soundButton.onclick=()=>{soundPanel.classList.toggle('open'); sceneMenu.classList.remove('open'); settingsPanel.classList.remove('open')};
 settingsButton.onclick=()=>{settingsPanel.classList.toggle('open'); sceneMenu.classList.remove('open'); soundPanel.classList.remove('open')};
 hintsToggle.checked=hintsEnabled; hintsToggle.onchange=e=>{hintsEnabled=e.target.checked; hint.classList.add('hidden');}; settingsLanguage.onchange=e=>setLanguage(e.target.value); settingsComicLanguage.onchange=e=>setComicLanguage(e.target.value,true); narratorToggle.onchange=e=>setNarratorEnabled(e.target.checked); settingsNarratorLanguage.onchange=e=>setNarratorLanguage(e.target.value); narratorVolumeSlider.oninput=e=>setNarratorVolume(e.target.value); narratorReplayButton.onclick=replayNarrator; narratorStopButton.onclick=stopNarrator; narratorRateSelect.onchange=e=>setNarratorRate(e.target.value); volumeSlider.oninput=e=>setVolume(e.target.value); previousButton.onclick=previousScene; nextButton.onclick=nextScene; restartButton.onclick=restart; replaySceneButton.onclick=replayScene; pauseButton.onclick=togglePause; hintButton.onclick=showHint;
 translatePlayerUI(); updateNarratorUI(); updateSceneUI(); loadComic(false);
 if(resizeObserver) resizeObserver.disconnect(); resizeObserver=new ResizeObserver(()=>syncViewport()); resizeObserver.observe(document.getElementById('stage'));
}
function translatePlayerUI(){if(!playerStarted && !document.getElementById('settingsTitle')) return; const set=(id,text)=>{const el=document.getElementById(id);if(el)el.textContent=text}; set('settingsTitle',t().settings); set('hintsLabel',t().hints); set('settingsLanguageLabel',t().language); set('settingsComicLanguageLabel',t().comicLanguage); set('musicVolumeLabel',t().musicVolume); set('narratorLabel',nt().narrator); set('settingsNarratorLanguageLabel',nt().voiceLanguage); set('narratorVolumeLabel',nt().narratorVolume); set('narratorReplayButton',nt().replay); set('narratorStopButton',nt().stop); set('previousButton',t().back); set('nextButton',t().next); set('restartButton',t().restart); set('replaySceneButton',t().replay); set('statusTitle',t().statusLabel); set('statusSceneTitle',t().statusScene); set('statusLanguageTitle',t().statusLanguage); const settingsLanguage=document.getElementById('settingsLanguage'); if(settingsLanguage) settingsLanguage.value=currentLanguage; const settingsComicLanguage=document.getElementById('settingsComicLanguage'); if(settingsComicLanguage) settingsComicLanguage.value=comicLanguage; const settingsNarratorLanguage=document.getElementById('settingsNarratorLanguage'); if(settingsNarratorLanguage){fillNarratorLanguageSelect(settingsNarratorLanguage); settingsNarratorLanguage.value=narratorLanguage} if(document.getElementById('statusValue')?.textContent==='') document.getElementById('statusValue').textContent=t().statusLoading; updateSoundUI(); updateNarratorUI(); if(playerStarted){document.getElementById('statusLanguageValue').textContent=comicLanguageNames[comicLanguage]||comicLanguage;}}
function launchPlayer(){if(playerStarted) return; launchButton.disabled=true; loading.classList.add('active'); setTimeout(()=>{preview.style.display='none'; createPlayer(); playerContainer.classList.add('loaded'); playerStarted=true; loading.classList.remove('active'); translatePlayerUI();}, 500);}
fillLanguageSelect(launchLanguage); comicLanguage=resolveDefaultComicLanguage(); fillComicLanguageSelect(launchComicLanguage); fillNarratorLanguageSelect(launchNarratorLanguage); buildPreviewStrip(); launchLanguage.onchange=e=>setLanguage(e.target.value); launchComicLanguage.onchange=e=>setComicLanguage(e.target.value,false); launchNarratorToggle.onchange=e=>setNarratorEnabled(e.target.checked); launchNarratorLanguage.onchange=e=>setNarratorLanguage(e.target.value); launchButton.onclick=launchPlayer; setLanguage('uk'); updateNarratorUI();
